### ISSUE TITLE
I migrate to swift3 and make some changes

### ISSUE THREAD

**Issue by futomtom** [zerdzhong/SwiftAudioQueueDemo#1]
如果你有興趣看看 在這裡 https://github.com/futomtom/audioqueue-swift3

**Comment by zerdzhong** [comment]
Pull requests are welcome。😁

**Comment by zerdzhong** [comment]
[https://github.com/zerdzhong/SwiftAudioQueueDemo/commit/aa34b660a483d1a03af5cc65cc0e6ee13958f607](url) migrate to swift3.
